stages:
  - build
  - deploy

# save node_modules from build to deploy
cache:
  paths:
    - node_modules
    - dist

build:
  stage: build
  script:
    - npm install
    - au build --env prod
  tags:
    - default

deploy:
  stage: deploy
  script:
    - /home/com.akaver.sportmap.aurelia/publish-aurelia.sh
  environment:
    name: release
  only:
    - master
  tags:
    - default
